### ISSUE TITLE
No useful error message when pre-processor fails

### ISSUE THREAD

**Issue by skogsbaer** [soenkehahn/dead-code-detection#12]
I tried dead-code-detection on a large project. After a while, it fails with

```
dead-code-detection: dead-code-detection: phase `C pre-processor' failed (exitcode = 1)
```

How can I get a mroe useful error message here?

**Comment by soenkehahn** [comment]
Thanks for the report.

I don't know of an easy way to obtain better error messages currently. :(

This is probably an error message that gets passed through from `ghc`. But of course it would be better if `dead-code-detection` could do a better job. Probably just a source location would help a lot. Not sure how hard that'd be. (This should definitely be fixed, not sure I'll get to it soon.)

My guess is that the issue is caused by some include files missing. `dead-code-detection` uses `ghc` directly and doesn't allow `ghc` to include the `cabal_macros.h` file, for example. Unfortunately it also doesn't allow to pass in flags to `ghc` to manually work around that. But that's a topic for another issue...

**Comment by soenkehahn** [comment]
@skogsbaer: If it's publicly available, could you point to the bigger project that you tried this on? That would help debug the issue.

**Comment by soenkehahn** [comment]
Working on this here: https://github.com/soenkehahn/dead-code-detection/tree/preprocessor-errors

**Comment by soenkehahn** [comment]
Uploaded to hackage as `0.8.1`.
