### ISSUE TITLE
Fails on Hoogle

### ISSUE THREAD

**Issue by ndmitchell** [soenkehahn/dead-code-detection#3]
Given a checkout of Hoogle from https://github.com/ndmitchell/hoogle I get:

```
C:\Neil\hoogle>dead-code-detection --root Main -isrc
dead-code-detection: Could not find module `Input.Type'
Use -v to see a list of the files searched for.

C:\Neil\hoogle>dead-code-detection --root Main -isrc -v
unrecognized option `-v'
```

The reason is that `src/Hoogle.hs` imports Input.Type. But `src/Hoogle.hs` isn't anywhere on the dependency graph from Root, so is unnecessary - it's a totally dead file which doesn't compile.

Saying use `-v` and then `-v` not working is a bit sad, but I suspect that's the GHC API doing it for you.

**Comment by soenkehahn** [comment]
Here's a PR that gives a more sensible error message: #5. The output now clearly states that the error message is from ghc. I hope this will result in less confusion. (If you don't agree, I'd like to hear about better ideas.)

Regarding the behavior apart from the error messages: `dead-code-detection` intentionally doesn't use `ghc` to resolve the dependencies, but looks at the file system itself. This way it can find dead code in modules that aren't imported anywhere. (And as you point out, `src/Hoogle.hs` is a totally dead file, so the tool should find and report it.) I do consider this an important feature and I tend to think this is the right default behavior.

Would you want to have a way to tweak this default behavior? How exactly would you imagine that to work?

Apart from that: If you just delete `src/Hoogle.hs` `dead-code-detection` seems to be working fine.

**Comment by ndmitchell** [comment]
Scanning the file system seems entirely reasonable. I'd be tempted to say that if a module can't be parsed you: 1) print out a message saying it can't be parsed, and 2) pretend it is a blank module with no uses and no exports. In this case seeing an error for this module, and then seeing useful results for the rest of the code, would be useful. In many of my projects I have `travis.hs` modules or similar that are only run on Travis, and where I might not have the necessary dependencies installed locally.

**Comment by ndmitchell** [comment]
I should say the behaviour of continuing would be nice, but not essential - it sounds like its now clear how to avoid the issue, so not a big problem if you decide to do nothing.

**Comment by soenkehahn** [comment]
In this case, the module could be parsed (or at least the import statements), but the imported modules couldn't be found.

In any case, I'll merge the changes in #5.

Regarding the idea to ignore modules with errors while warning about them: I wonder if this would be bad behavior in the case where your project actually doesn't compile, because you have a type error or the like. You would see a warning that one module doesn't compile, but then all other modules that (transitively) import that module would also not compile. And also issue a warning, that they don't compile? So you end up with a bunch of warnings for every module?

I always liked the idea that a prerequisite of `dead-code-detection` is, that your project (and every file in it) compiles.

But I can perfectly see, why you'd want to have files like `travis.hs` (or other scripts) that you want to exclude from being analyzed. What do you think about an additional command line flag to ignore certain files. For example:

``` bash
dead-code-detection --root Main -isrc --ignore src/Hoogle.hs
```

**Comment by ndmitchell** [comment]
An ignore flag works too, and is probably the simplest and most direct solution.

**Comment by soenkehahn** [comment]
I've opened #8 and #7 instead of this ticket, therefore closing this. If you have further problems with `hoogle`, please, re-open.
